name: Generate dist

on:
  push:
    branches:
      - main
      - "develop*"
      - feature/ppcp-web-ci-pipeline # todo remove me
      - "hotfix/*"

jobs:
  generate-dist:
    runs-on: ubuntu-latest

    steps:

      - name: Prepare git
        shell: bash
        run: |
          git config --global user.name "github-action[bot]"
          git config --global user.email "github-action[bot]@users.noreply.github.com"

      - name: Check out the src branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Generate dist
        shell: bash
        run: |
          set -v
                    
          git config --global pull.rebase false
          git fetch --unshallow || true

          cd view/frontend/web/js/checkout/
          
          echo "cloning ppcp-web until it is made public"
          git clone https://x-access-token:${{ secrets.GH_PPCP_WEB_PAT }}@github.com/BlueFinchCommerce/ppcp-web.git 
          
          rm package-lock.json  
          npm i --verbose
          npm run build
          git add -f ./dist

          git status

          if ! git diff-index --quiet HEAD; then
            echo "Adding changes to git"
            git commit -am "[bot] generate dist ($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
            git push
          else
            echo "exiting"
            exit 0;
          fi

